### ISSUE TITLE
[Question] Is this project Laravel-4 only?

### ISSUE THREAD

**Issue by shehi** [barryvdh/laravel-assetic#10]
Is this project Laravel-4 only? I ask coz readme doesn't specify.

**Comment by barryvdh** [comment]
Yes and discontinued

**Comment by shehi** [comment]
Oh man. I hate the lack of Assetic documentation. I can't figure out why `$writer->writeManagerAssets()` of Assetic's throws "Unable to write file" error, unless I define `setTargetPath()` for each asset - why the hell base-path defined at `new AssetFactory('/base/path');` doesn't work?!

@barryvdh , do you know ANY source which could help me with Laravel-Twig-Assetic trio implementation?
