### ISSUE TITLE
Is there a plan to release this for Laravel5?

### ISSUE THREAD

**Issue by jdcrecur** [barryvdh/laravel-assetic#11]
The laravel mix is too restricting and prefer to use our own front end build setups. This then means we are looking for an alternative front-end asset management tool. This would be perfect if it worked in 5.

**Comment by barryvdh** [comment]
Nope

**Comment by jdcrecur** [comment]
How come?

**Comment by barryvdh** [comment]
Because I don't use it anymore. Perfectly happy with Mix

**Comment by jdcrecur** [comment]
How do you develop bigger apps with a front end repo and backend api repo on laravel? Still merging it all into one app?

**Comment by barryvdh** [comment]
If the back-end is an API, why would you need front-end assets?

Anyways, you're free to fork this and upgrade it to L5.5. But I don't use it, so no plans to maintain it. (Hasn't been touched in 3 years..)

**Comment by jdcrecur** [comment]
We have clients with internal networks and limited subdomains... when we build apps we like to keep the frontend repo and backend repo separate. As we are stuck with a single domain and sub domain the easiest thing to do is deploy the front end as a git sub-module in the backend stack... hence our search for assetic/laravel plugin.
