### ISSUE TITLE
Usage of assetic

### ISSUE THREAD

**Issue by aditya-** [barryvdh/laravel-assetic#4]
Hi ,

I want to use this for my laravel 4.0 app . previously i have used codeselve asset-pipeline which given me some bad results ... now i want to try assetic package for my laravel app 

before using i have few doubts .. can you please clarify :
1. is this packages is based on kriswallsmith-assetic  ?
   https://github.com/kriswallsmith/assetic  

2.in my old asset-pipeline i can add group of css and js files with single command like = require_tree . using this i can  add all the file at the same time .. 
Here how to ad css and js files and is there any way to add files in the folder at the same time ..
1. Please let me anything other i need to implement in my app inorder to make this work .. please let me know ..

Thanks

**Comment by barryvdh** [comment]
1. yes, it is based on Assetic
2. You can probably do that, just look at the docs from assetic.

**Comment by aditya-** [comment]
@barryvdh  .. thank you

May i know .. How to implement this framework .. like suppose i want to include files in a css folder .. then where i need to mention .. will it minifes css and js files ?  will it optimizes images ?

**Comment by barryvdh** [comment]
It should do anything that https://github.com/kriswallsmith/assetic does, this is just a wrapper to easily register Assetic. Look at the docs there. 
You can also publish the config to use the FilterManager.

But I'm sorry, I don't really have any time to explain everything, I created this package mainly to easily use Assetic within Twig, but I'm shifting to Gulp to move asset handling out of PHP.

**Comment by aditya-** [comment]
@barryvdh  atleast can you tell .. how to include a filter .. suppose if want to use JpegoptimFilter .. then what i need to include .. where .. ..etc

**Comment by barryvdh** [comment]
Publish the config file (`php artisan config:publish barryvdh/laravel-assetic`) and change the AssetManager.
This is an example I used:

```
// app/config/packages/barryvdh/laravel-assetic/config.php
 'asset_manager' => function(AssetManager $am){

          $am->set('style', new AssetCollection(array(
              new FileAsset('less/style.less', array(new \Assetic\Filter\LessphpFilter())),
          )), new Assetic\Filter\CssRewriteFilter());
          $am->get('style')->setTargetPath('assets/style.css');

          $am->set('scriptFooter', new AssetCollection(array(
              new FileAsset('js/bootstrap.min.js'),
              new FileAsset('js/jquery.validate.js'),
              new FileAsset('js/script.js'),
          )), new Assetic\Filter\JSMinFilter);
          $am->get('scriptFooter')->setTargetPath('assets/script-footer.js');

          $am->set('scriptHead', new AssetCollection(array(
              new FileAsset('js/modernizr.js'),
          )), new Assetic\Filter\JSMinFilter);
          $am->get('scriptHead')->setTargetPath('assets/script-head.js');
  },
```

Here is an example of the library this is based on: https://github.com/mheap/Silex-Assetic/blob/master/example/assetic.php#L30

**Comment by barryvdh** [comment]
Sorry I'm not a helpdesk.

**Comment by aditya-** [comment]
@barryvdh  .. but thanks for  your time till now ... thank you
